<<<<<<< HEAD
# Generated by Django 4.1.2 on 2023-06-22 10:21

=======
>>>>>>> b1999d3d7ff74dc4b5437d30557a1bc46edeac3c
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("wagtailcore", "0083_workflowcontenttype"),
=======
        ("wagtailcore", "0076_modellogentry_revision"),
>>>>>>> b1999d3d7ff74dc4b5437d30557a1bc46edeac3c
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(verbose_name="Post date")),
                ("intro", models.CharField(max_length=250)),
                ("body", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
