# Generated by Django 4.2.2 on 2023-06-30 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_blogpage_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="categories",
        ),
        migrations.DeleteModel(
            name="BlogCategory",
        ),
    ]
