# Generated by Django 4.1.2 on 2023-06-23 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blogtagindexpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogTagIndexPage",
        ),
    ]
