# Generated by Django 4.1.2 on 2023-06-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("blog", "0009_blogtagindexpage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogCategory",
            new_name="Author",
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "blog authors"},
        ),
        migrations.RenameField(
            model_name="author",
            old_name="icon",
            new_name="author_image",
        ),
        migrations.RenameField(
            model_name="blogpage",
            old_name="categories",
            new_name="authors",
        ),
    ]
