# Generated by Django 4.1.2 on 2023-06-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_rename_blogcategory_author_alter_author_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "Authors"},
        ),
    ]
