<<<<<<< HEAD
# Generated by Django 4.1.2 on 2023-06-22 09:29

=======
>>>>>>> b1999d3d7ff74dc4b5437d30557a1bc46edeac3c
from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
